export type ProjectLink = { label: string; href: string };

export type ProjectAccess = {
  label: "Demo pública" | "Repositorio público" | "Caso documentado" | "Despliegue privado";
  detail: string;
};

export type ProjectGroupId = "commerce" | "automation" | "infrastructure";

export type ProjectGroup = {
  id: ProjectGroupId;
  index: string;
  label: string;
  description: string;
};

export type Project = {
  slug: string;
  title: string;
  category: string;
  group: ProjectGroupId;
  year: string;
  index: string;
  summary: string;
  description: string[];
  result: string;
  stack: string[];
  cover?: string;
  coverAlt?: string;
  coverPosition?: string;
  gallery: string[];
  links: ProjectLink[];
  access: ProjectAccess;
  featured?: boolean;
  tone: "orange" | "ink" | "sand";
};

const projectEntries: Project[] = [
  {
    slug: "tienda-mamayucca",
    title: "Tienda Mamayucca",
    category: "Comercio digital + producto",
    group: "commerce",
    year: "2026",
    index: "01",
    summary: "Tienda pública para presentar productos misioneros, recetas y recorridos de compra minorista y mayorista.",
    description: [
      "La experiencia reúne catálogo, recetas, contenido de producto y recorridos diferenciados para consumidor, reventa y distribución. El sitio prioriza fotografía, claridad de compra y contacto directo.",
      "La demo se puede recorrer sin login. Las operaciones internas y los servicios administrativos permanecen fuera del portfolio.",
    ],
    result: "Una vidriera comercial verificable que conecta marca, contenido y venta sin exponer la operación privada.",
    stack: ["Next.js", "E-commerce", "Diseño responsive", "WhatsApp", "Contenido"],
    cover: "/project-covers/mamayucca-store.png",
    coverAlt: "Página principal pública de Tienda Mamayucca con Farofa y Cheyuyo",
    gallery: [],
    links: [{ label: "Abrir demo pública", href: "https://www.mamayucca.com/" }],
    access: { label: "Demo pública", detail: "Verificada sin login el 27 de agosto de 2026. El repositorio no está publicado." },
    featured: true,
    tone: "sand",
  },
  {
    slug: "agroveterinaria-gross",
    title: "Agroveterinaria Gross",
    category: "Sistema + e-commerce",
    group: "commerce",
    year: "2026",
    index: "02",
    summary: "E-commerce para una veterinaria, pet shop y farmacia con catálogo, ofertas, búsqueda y compra online.",
    description: [
      "El caso reúne dos superficies públicas: una web institucional orientada a servicios y turnos, y un e-commerce con búsqueda, categorías, ofertas, productos y medios de contacto.",
      "El sistema operativo que sostiene catálogo y gestión queda documentado como parte del caso, pero sus paneles y accesos administrativos no se publican.",
    ],
    result: "Una presencia digital conectada: comunicación institucional, catálogo comercial y operación privada con límites de acceso explícitos.",
    stack: ["E-commerce", "Catálogo", "Pagos", "Diseño responsive", "Operaciones"],
    cover: "/project-covers/gross-hero.gif",
    coverAlt: "Hero animado de la tienda pública de Agroveterinaria Gross",
    gallery: [
      "/project-covers/gross-commerce.png",
      "/project-covers/gross-store.png",
      "/project-covers/gross-site.png",
    ],
    links: [
      { label: "Abrir sitio institucional", href: "https://www.agroveterinariagross.com.ar/" },
      { label: "Abrir tienda pública", href: "https://agroveterinariagross.zubuagency.com/" },
    ],
    access: { label: "Demo pública", detail: "Las dos superficies fueron verificadas sin login. El panel del sistema permanece privado." },
    featured: true,
    tone: "orange",
  },
  {
    slug: "zubu-agency",
    title: "ZUBU Agency",
    category: "Agencia + software + automatización",
    group: "commerce",
    year: "2026",
    index: "03",
    summary: "Agencia cofundada por Tobías para diseñar software, automatizaciones, bots, integraciones y experiencias web.",
    description: [
      "Tobías cofundó ZUBU Agency en 2026. La agencia combina relevamiento, diseño, software a medida, automatización e IA aplicada para negocios y PyMEs.",
      "No es sólo una landing: es la estructura desde la que se construyeron tiendas, sistemas internos, catálogos, bots e integraciones para distintos rubros.",
    ],
    result: "Una puerta de entrada comercial con propuesta, servicios, demostración conversacional y contacto en el mismo recorrido.",
    stack: ["React", "TypeScript", "Automatización", "IA aplicada", "Diseño web"],
    cover: "/project-covers/zubu-agency-2026.png",
    coverAlt: "Página principal pública de ZUBU Agency",
    gallery: [],
    links: [
      { label: "Abrir landing pública", href: "https://zubuagency.com/" },
      { label: "Ver Instagram", href: "https://www.instagram.com/zubuagency/" },
      { label: "Ver repositorio", href: "https://github.com/trobias/ZUBU3" },
    ],
    access: { label: "Demo pública", detail: "Dominio activo y repositorio público verificados. El deploy anterior de Vercel responde 404." },
    featured: true,
    tone: "ink",
  },
  {
    slug: "emag-subot",
    title: "EMAG + SUBOT / Pedidos por WhatsApp",
    category: "Bot + automatización de pedidos",
    group: "automation",
    year: "2025",
    index: "04",
    summary: "Un carrito completo dentro de WhatsApp: catálogo, stock, ubicación, pagos y derivación a una persona.",
    description: [
      "EMAG traslada la lógica de un e-commerce al chat. El cliente elige productos, modifica cantidades, confirma su ubicación y recibe un enlace de pago sin salir de la conversación.",
      "n8n orquesta el flujo, Postgres conserva cada carrito por chat y Evolution API conecta la mensajería. La IA se reserva para interpretar intención cuando aporta valor.",
    ],
    result: "Un flujo de venta de punta a punta, trazable y preparado para continuar con un distribuidor humano.",
    stack: ["n8n", "Postgres", "Evolution API", "Mercado Pago", "Docker", "JavaScript"],
    cover: "/proyectos/web-ia-n8n/emag/workflow-n8n.jpg",
    coverAlt: "Flujo de automatización de pedidos EMAG en n8n",
    gallery: [
      "/proyectos/web-ia-n8n/emag/whatsapp-bienvenida.jpg",
      "/proyectos/web-ia-n8n/emag/whatsapp-catalogo.jpg",
      "/proyectos/web-ia-n8n/emag/crud-carrito.jpg",
      "/proyectos/web-ia-n8n/emag/mercadopago-link.jpg",
    ],
    links: [
      { label: "Ver repositorio", href: "https://github.com/trobias/BotdePedidosPorWhatsappEMAGAplicacionInteligente" },
    ],
    access: { label: "Repositorio público", detail: "El código del bot es público; no se enlaza una instancia de WhatsApp en producción." },
    tone: "orange",
  },
  {
    slug: "jarvis-workspace",
    title: "Jarvis / Workspace en WhatsApp",
    category: "Automatización + IA",
    group: "automation",
    year: "2025",
    index: "05",
    summary: "Un asistente que convierte mensajes y audios en acciones sobre Gmail, Calendar, Drive y Sheets.",
    description: [
      "Jarvis conecta Google Workspace con WhatsApp para enviar y leer correos, crear eventos, buscar archivos y responder consultas desde una interfaz conversacional familiar.",
      "La IA entiende el pedido, mientras flujos modulares de n8n llaman a las APIs oficiales y confirman cada acción.",
    ],
    result: "Un hub personal de trabajo que reduce pasos sin ocultar qué acción fue ejecutada.",
    stack: ["n8n", "Google APIs", "Evolution API", "Gemini", "OpenAI", "Docker"],
    cover: "/proyectos/web-ia-n8n/jarvis/jarvis-flow.jpg",
    coverAlt: "Flujo modular del asistente Jarvis",
    gallery: [
      "/proyectos/web-ia-n8n/jarvis/whatsapp.jpg",
      "/proyectos/web-ia-n8n/jarvis/google-sheets.jpg",
      "/proyectos/web-ia-n8n/jarvis/calendar.jpg",
      "/proyectos/web-ia-n8n/jarvis/audio.jpg",
    ],
    links: [{ label: "Ver repositorio", href: "https://github.com/trobias/JARVIS-GOOGLEWORKSPACE-WHATSAPPCHATBOT" }],
    access: { label: "Repositorio público", detail: "No se publica una demo porque requiere cuentas y permisos de Google Workspace." },
    tone: "ink",
  },
  {
    slug: "facturacion-mercadopago-arca",
    title: "Facturación Mercado Pago + ARCA",
    category: "Finanzas + automatización",
    group: "automation",
    year: "2026",
    index: "06",
    summary: "Integración para conectar cobros de Mercado Pago con el circuito de facturación fiscal de ARCA/exAFIP.",
    description: [
      "El caso documenta la conexión entre eventos de pago y el proceso de facturación, con foco en trazabilidad, estados y tratamiento de errores.",
      "Por tratarse de una operación fiscal y financiera, no se publica una demo ni se exponen credenciales, comprobantes reales o paneles administrativos. El detalle técnico definitivo sigue pendiente de validación.",
    ],
    result: "Caso privado en documentación: la ficha explica la arquitectura sin revelar datos fiscales ni accesos operativos.",
    stack: ["Mercado Pago", "ARCA / exAFIP", "Automatización", "APIs", "Facturación"],
    gallery: [],
    links: [],
    access: { label: "Caso documentado", detail: "Sin demo ni repositorio público confirmados. Se mantiene una explicación interna por seguridad." },
    featured: true,
    tone: "sand",
  },
  {
    slug: "erp-mamayucca",
    title: "ERP Mamayucca",
    category: "Operaciones + software",
    group: "automation",
    year: "2026",
    index: "07",
    summary: "Sistema interno para centralizar la operación de Mamayucca y conectar información comercial en un único flujo.",
    description: [
      "El ERP centraliza pedidos, producción, inventario, compras, clientes, vendedores, envíos, contabilidad, facturación y auditoría dentro del ecosistema Mamayucca.",
      "El código local confirma Next.js, React, TypeScript, Supabase, validación, pruebas y una integración fiscal. Las pantallas operativas siguen fuera del portfolio hasta aprobar una captura desensibilizada.",
    ],
    result: "Caso interno preparado para crecer con evidencia validada, sin convertir una hipótesis de alcance en una afirmación pública.",
    stack: ["Next.js", "React", "TypeScript", "Supabase", "ERP", "ARCA"],
    gallery: [],
    links: [],
    access: { label: "Despliegue privado", detail: "El despliegue redirige a un acceso por PIN. No se publican paneles, credenciales ni URL administrativas." },
    tone: "ink",
  },
  {
    slug: "bot-mamayucca",
    title: "Bot Mamayucca",
    category: "Conversación + automatización",
    group: "automation",
    year: "2026",
    index: "08",
    summary: "Automatización conversacional vinculada al ecosistema comercial de Mamayucca.",
    description: [
      "El proyecto se incorpora como caso independiente para explicar la capa conversacional sin confundirla con la tienda frontend o el ERP.",
      "Las funciones, canales, integraciones y métricas todavía no cuentan con evidencia pública suficiente. La página conserva esos puntos como abiertos en vez de inventarlos.",
    ],
    result: "Una ficha privada lista para recibir capturas desensibilizadas, diagrama y resultados cuando estén autorizados.",
    stack: ["Automatización", "Mensajería", "Integraciones"],
    gallery: [],
    links: [],
    access: { label: "Caso documentado", detail: "Sin demo ni repositorio público confirmados." },
    tone: "orange",
  },
  {
    slug: "tienda-emag",
    title: "Tienda EMAG",
    category: "Web + comercio mayorista",
    group: "commerce",
    year: "2026",
    index: "09",
    summary: "Tienda pública de refrigerantes y agua destilada con catálogo, formatos, stock y contacto mayorista.",
    description: [
      "La versión principal presenta la línea de productos de EMAG, sus formatos y disponibilidad con un recorrido comercial directo.",
      "El hero usa video propio y la navegación pública funciona sin login. El repositorio de esta versión permanece privado.",
    ],
    result: "Una superficie comercial rápida que acerca producto, stock y pedido por WhatsApp en un único recorrido.",
    stack: ["Next.js", "React", "TypeScript", "GSAP", "E-commerce", "WhatsApp"],
    cover: "/project-covers/emag-hero.gif",
    coverAlt: "Hero animado de Tienda EMAG con refrigerante y agua destilada",
    gallery: ["/project-covers/emag-store.png"],
    links: [{ label: "Abrir tienda pública", href: "https://refrigerantesemag.vercel.app/" }],
    access: { label: "Demo pública", detail: "Tienda verificada sin login el 28 de agosto de 2026; el repositorio es privado." },
    featured: true,
    tone: "orange",
  },
  {
    slug: "emag-inmersivo-gsap",
    title: "EMAG Inmersivo / GSAP",
    category: "Experiencia web + scroll",
    group: "commerce",
    year: "2026",
    index: "10",
    summary: "Variante experimental de EMAG donde el producto, la tipografía y el scroll construyen una narrativa inmersiva.",
    description: [
      "La ruta /home2 trata la misma marca como una experiencia distinta: hero sticky, escenas por scroll, movimiento reversible y una composición de producto más cinematográfica.",
      "GSAP y ScrollTrigger coordinan transformaciones y estados; el contenido conserva una versión completa cuando el usuario reduce el movimiento.",
    ],
    result: "Una exploración de dirección de arte y movimiento que convierte el catálogo en una historia de producto sin perder acceso a la compra.",
    stack: ["Next.js", "React", "TypeScript", "GSAP", "ScrollTrigger", "CSS Modules"],
    cover: "/project-covers/emag-immersive.png",
    coverAlt: "Hero de la variante inmersiva de EMAG con producto y tipografía monumental",
    gallery: ["/project-covers/emag-hero.gif"],
    links: [{ label: "Abrir experiencia inmersiva", href: "https://refrigerantesemag.vercel.app/home2" }],
    access: { label: "Demo pública", detail: "Variante verificada sin login el 28 de agosto de 2026; el repositorio es privado." },
    featured: true,
    tone: "ink",
  },
  {
    slug: "misiones-muebles",
    title: "Misiones Muebles",
    category: "Sistema + comercio",
    group: "commerce",
    year: "2026",
    index: "09",
    summary: "ERP interno para ventas, caja, pedidos, producción, entregas, inventario, compras, personal y auditoría.",
    description: [
      "El repositorio local documenta una aplicación interna para una mueblería de Posadas, con circuitos conectados de venta, stock, producción, entrega, caja y cuenta corriente.",
      "La aplicación usa datos operativos y autenticación por roles. Por privacidad no se publica el despliegue ni una captura del panel hasta contar con una vista desensibilizada aprobada.",
    ],
    result: "El despliegue se reconoce sin publicar la dirección del panel, identificadores internos ni supuestos sobre su funcionamiento.",
    stack: ["Next.js", "React", "TypeScript", "Prisma", "PostgreSQL", "Zod", "Dokploy"],
    gallery: [],
    links: [],
    access: { label: "Despliegue privado", detail: "Se necesita acceso autenticado o una URL pública autorizada para completar la evidencia." },
    tone: "sand",
  },
  {
    slug: "nico-scraper",
    title: "Nico Scraper",
    category: "Datos + automatización",
    group: "automation",
    year: "2026",
    index: "10",
    summary: "Proyecto de extracción y procesamiento de datos pendiente de documentación pública.",
    description: [
      "El nombre confirma su naturaleza de scraping, pero todavía no hay una fuente pública que permita afirmar origen de datos, frecuencia, salida o tecnologías específicas.",
      "La página interna sirve como contenedor para completar objetivo, pipeline, límites legales, tratamiento de errores y una muestra desensibilizada.",
    ],
    result: "Caso preparado para documentar el pipeline sin publicar fuentes privadas ni datos recolectados.",
    stack: ["Scraping", "Datos", "Automatización"],
    gallery: [],
    links: [],
    access: { label: "Caso documentado", detail: "Sin demo ni repositorio público confirmados." },
    tone: "ink",
  },
  {
    slug: "ceferina-accesorios",
    title: "Ceferina Accesorios",
    category: "Comercio digital",
    group: "commerce",
    year: "2026",
    index: "11",
    summary: "Tienda de accesorios de satén hechos a mano, con catálogo, carrito y pedido directo por WhatsApp.",
    description: [
      "La experiencia presenta scrunchies, moños, gorros, rizadores y combos mediante una identidad cálida y una navegación comercial directa.",
      "La demo pública puede recorrerse sin login. El repositorio existe pero es privado, por lo que no se enlaza desde el portfolio.",
    ],
    result: "Una tienda compacta que convierte una identidad artesanal en catálogo y consulta sin sumar fricción.",
    stack: ["Next.js", "React", "TypeScript", "E-commerce", "WhatsApp", "SEO"],
    cover: "/project-covers/ceferina.png",
    coverAlt: "Hero público de Ceferina Accesorios con un scrunchie negro",
    gallery: [],
    links: [{ label: "Abrir tienda pública", href: "https://ceferina-accesorios.vercel.app/" }],
    access: { label: "Demo pública", detail: "Tienda verificada sin login el 28 de agosto de 2026; el repositorio es privado." },
    featured: true,
    tone: "orange",
  },
  {
    slug: "yeryos",
    title: "Yeryos",
    category: "E-commerce + marca",
    group: "commerce",
    year: "2026",
    index: "12",
    summary: "Tienda pública de mates, blends y bombillas construida alrededor de la idea de compartir momentos.",
    description: [
      "La experiencia organiza categorías, momentos, catálogo y orientación de compra dentro de una identidad visual cálida y enfocada en el ritual matero.",
      "La demo puede recorrerse sin login. No se publica un repositorio porque no fue confirmado como público.",
    ],
    result: "Una superficie comercial pública que conecta catálogo, identidad y consulta directa.",
    stack: ["E-commerce", "Catálogo", "Diseño responsive", "Marca"],
    cover: "/project-covers/yeryos-hero.gif",
    coverAlt: "Hero animado de la tienda Yeryos con mate, blends y bombillas",
    gallery: ["/project-covers/yeryos.png"],
    links: [{ label: "Abrir tienda pública", href: "https://yeryos.zubuagency.com/" }],
    access: { label: "Demo pública", detail: "Tienda verificada sin login el 27 de agosto de 2026." },
    featured: true,
    tone: "sand",
  },
  {
    slug: "zuzaniuk",
    title: "Zuzaniuk",
    category: "Producto digital",
    group: "commerce",
    year: "2026",
    index: "13",
    summary: "Closet digital local-first con análisis visual asistido por IA y una experiencia editorial inmersiva.",
    description: [
      "El producto permite organizar prendas, combinarlas y enriquecerlas con análisis visual sin exigir una cuenta para empezar.",
      "El repositorio local confirma Next.js, React, TypeScript, Tailwind, Motion y GSAP. El repositorio remoto es privado y no existe una demo pública confirmada.",
    ],
    result: "Un prototipo funcional de producto personal donde la privacidad local y la asistencia visual conviven en el mismo recorrido.",
    stack: ["Next.js", "React", "TypeScript", "Motion", "GSAP", "IA visual", "Local-first"],
    cover: "/project-covers/zuzaniuk-hero.gif",
    coverAlt: "Secuencia animada del closet digital Zuzaniuk",
    gallery: [],
    links: [],
    access: { label: "Caso documentado", detail: "Evidencia revisada en el repositorio local; código remoto privado y sin demo pública confirmada." },
    tone: "ink",
  },
  {
    slug: "ordenya",
    title: "ERP OrdenYa",
    category: "ERP + operaciones",
    group: "automation",
    year: "2026",
    index: "15",
    summary: "Sistema de gestión protegido para administrar la operación comercial de OrdenYa.",
    description: [
      "El ERP concentra la operación interna y se mantiene separado de la tienda pública para que cada producto tenga un propósito y un nivel de acceso claros.",
      "La URL conduce a un acceso por usuario y PIN. No se publica como demo ni se incluyen capturas administrativas sin una versión desensibilizada.",
    ],
    result: "Una capa operativa independiente de la experiencia de compra pública.",
    stack: ["ERP", "Operaciones", "Pedidos", "Datos", "Autenticación"],
    gallery: [],
    links: [],
    access: { label: "Despliegue privado", detail: "El ERP requiere usuario y PIN; la URL operativa no se presenta como demo." },
    tone: "orange",
  },
  {
    slug: "tienda-ordenya",
    title: "Tienda OrdenYa",
    category: "E-commerce + catálogo B2B/B2C",
    group: "commerce",
    year: "2026",
    index: "16",
    summary: "Catálogo público de productos naturales con recorridos de compra para distintos segmentos comerciales.",
    description: [
      "La tienda organiza catálogo, precios y pedidos dentro de una superficie pública independiente del ERP.",
      "Puede recorrerse sin login y funciona como demostración del frente comercial de OrdenYa.",
    ],
    result: "Una experiencia comercial abierta que preserva la privacidad del sistema de gestión conectado.",
    stack: ["E-commerce", "Catálogo", "B2B / B2C", "Mercado Pago", "Pedidos"],
    cover: "/project-covers/ordenya-natural.png",
    coverAlt: "Catálogo público de OrdenYa con productos naturales",
    gallery: [],
    links: [{ label: "Abrir tienda pública", href: "https://ordenya.zubuagency.com/natural" }],
    access: { label: "Demo pública", detail: "Catálogo verificado sin login el 28 de agosto de 2026." },
    tone: "sand",
  },
  {
    slug: "linkedin-rag",
    title: "Asistente IA para RR.HH.",
    category: "Automatización + IA",
    group: "automation",
    year: "2025",
    index: "19",
    summary: "Búsqueda semántica y respuestas con contexto sobre perfiles y empresas de LinkedIn.",
    description: [
      "Un asistente conversacional para Recursos Humanos que combina datos de LinkedIn con recuperación aumentada por generación (RAG).",
      "Cohere genera embeddings, FAISS indexa el contenido y LangChain recupera el contexto antes de construir cada respuesta en Streamlit.",
    ],
    result: "Consultas de RR.HH. con contexto verificable, en vez de respuestas genéricas del modelo.",
    stack: ["Python", "Cohere", "FAISS", "LangChain", "Streamlit", "RapidAPI"],
    cover: "/proyectos/web-ia-n8n/linkedinia/cover.jpg",
    coverAlt: "Interfaz del asistente de IA para Recursos Humanos",
    gallery: ["/proyectos/web-ia-n8n/linkedinia/streamlit-home.jpg", "/proyectos/web-ia-n8n/linkedinia/librerias.jpg"],
    links: [
      { label: "Ver repositorio", href: "https://github.com/trobias/AsistenteIALinkedIn" },
      { label: "Leer informe", href: "/proyectos/web-ia-n8n/linkedinia/AsistenteIALinkedIn.pdf" },
    ],
    access: { label: "Repositorio público", detail: "Código e informe disponibles públicamente." },
    tone: "sand",
  },
  {
    slug: "simulador-procesos",
    title: "Procesos en memoria / Arduino",
    category: "Hardware + IoT",
    group: "infrastructure",
    year: "2025",
    index: "20",
    summary: "Representación física del manejo de memoria y procesos de un sistema operativo, construida con LEDs y Arduino.",
    description: [
      "Cada proceso y bloque de memoria se representa mediante módulos y LEDs controlados por Arduino.",
      "Una interfaz en Python coordina la simulación y permite observar asignación, ejecución y liberación de recursos.",
    ],
    result: "Una herramienta didáctica donde software, electrónica y explicación trabajan como un único sistema.",
    stack: ["Arduino", "Python", "Electrónica", "Sistemas operativos", "Prototipado"],
    cover: "/proyectos/arduino-iot/simulador-procesos/cover.jpg",
    coverAlt: "Interfaz del simulador de gestión de procesos y memoria",
    gallery: ["/images/arduino.jpeg"],
    links: [
      { label: "Ver repositorio", href: "https://github.com/trobias/Process-Simulator" },
      { label: "Leer informe", href: "/proyectos/arduino-iot/simulador-procesos/simulador.pdf" },
    ],
    access: { label: "Repositorio público", detail: "Código, informe y material del prototipo disponibles." },
    tone: "ink",
  },
  {
    slug: "nutriado",
    title: "Nutriado / Asistente nutricional",
    category: "Automatización + IA",
    group: "automation",
    year: "2025",
    index: "21",
    summary: "Landing y asistente nutricional con IA, automatizaciones y persistencia de datos.",
    description: [
      "Nutriado combina una experiencia web liviana con un asistente capaz de orientar consultas nutricionales y conectar la conversación con flujos de automatización.",
      "La demo pública se presenta como evidencia del producto, no como asesoramiento médico.",
    ],
    result: "Una interfaz simple para acceder a una lógica de automatización más compleja.",
    stack: ["JavaScript", "IA", "n8n", "Base de datos", "Vercel"],
    cover: "/project-covers/nutriado.png",
    coverAlt: "Página pública del asistente nutricional Nutriado",
    gallery: [],
    links: [
      { label: "Abrir demo pública", href: "https://nutriadoai.vercel.app/" },
      { label: "Ver repositorio", href: "https://github.com/trobias/NUTRIADO" },
    ],
    access: { label: "Demo pública", detail: "Demo y repositorio público verificados." },
    tone: "sand",
  },
  {
    slug: "nuevo-quaranta",
    title: "Nuevo Quaranta / Espacio 3D",
    category: "Diseño + 3D",
    group: "infrastructure",
    year: "2024",
    index: "22",
    summary: "Modelado arquitectónico para planificar una transformación espacial antes de construirla.",
    description: ["Reconstrucción de un espacio en SketchUp para evaluar distribución, materiales e iluminación.", "La galería documenta planos, vistas de detalle y renders finales."],
    result: "Una visualización concreta para alinear idea, escala y ejecución.",
    stack: ["SketchUp", "AutoCAD", "Modelado 3D", "Render", "Diseño espacial"],
    cover: "/proyectos/adobes-3d/nuevoquaranta/cover.jpg",
    coverAlt: "Render del proyecto espacial Nuevo Quaranta",
    gallery: [
      "/proyectos/adobes-3d/nuevoquaranta/foto1.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto2.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto3.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto4.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto5.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto6.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto7.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto8.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto9.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto10.jpg",
      "/proyectos/adobes-3d/nuevoquaranta/foto11.jpg",
    ],
    links: [],
    access: { label: "Caso documentado", detail: "Galería completa de renders arquitectónicos incluida en el portfolio." },
    tone: "orange",
  },
  {
    slug: "hackobo",
    title: "Hackobo / Seguridad de redes",
    category: "Redes + seguridad",
    group: "infrastructure",
    year: "2024",
    index: "23",
    summary: "Análisis de vulnerabilidades y documentación de una práctica académica de pentesting.",
    description: ["Relevamiento de superficie, pruebas controladas y recomendaciones de hardening.", "El foco está tanto en el procedimiento técnico como en la claridad del informe final."],
    result: "Hallazgos comunicados con contexto, impacto y próximos pasos concretos.",
    stack: ["Pentesting", "Redes", "Análisis de vulnerabilidades", "Documentación"],
    cover: "/proyectos/redes-infra/Hackobo/cover.jpg",
    coverAlt: "Portada del informe de seguridad Hackobo",
    gallery: [],
    links: [{ label: "Leer informe", href: "/proyectos/redes-infra/Hackobo/HACKOBO.pdf" }],
    access: { label: "Caso documentado", detail: "Informe académico disponible dentro del portfolio." },
    tone: "ink",
  },
  {
    slug: "animabed",
    title: "Animabed / E-commerce circular",
    category: "Desarrollo web",
    group: "commerce",
    year: "2024",
    index: "24",
    summary: "E-commerce académico para camas de mascotas fabricadas con neumáticos recuperados.",
    description: ["Catálogo, carrito, registro y panel de administración para una marca académica de economía circular.", "La aplicación se desarrolló en PHP y MySQL con operaciones CRUD completas."],
    result: "Un sistema web completo alrededor de una propuesta de reutilización de materiales.",
    stack: ["PHP", "MySQL", "HTML", "CSS", "CRUD"],
    cover: "/proyectos/web-ia-n8n/animabed/cover.jpg",
    coverAlt: "Página principal del e-commerce académico Animabed",
    gallery: [
      "/proyectos/web-ia-n8n/animabed/catalogo.jpg",
      "/proyectos/web-ia-n8n/animabed/detalle.jpg",
      "/proyectos/web-ia-n8n/animabed/planos.jpg",
      "/proyectos/web-ia-n8n/animabed/admin.jpg",
      "/proyectos/web-ia-n8n/animabed/basededatos.jpg",
    ],
    links: [],
    access: { label: "Caso documentado", detail: "Capturas propias preservadas; sin demo pública activa." },
    tone: "orange",
  },
  {
    slug: "gns3-topologia",
    title: "Topología dinámica / GNS3",
    category: "Redes + seguridad",
    group: "infrastructure",
    year: "2024",
    index: "25",
    summary: "Simulación de una red con routers, switches y protocolos de enrutamiento dinámico.",
    description: ["Topología completa en GNS3 con configuración, enrutamiento y pruebas de conectividad.", "La red se valida antes de llevar decisiones a infraestructura física."],
    result: "Una topología reproducible con decisiones y pruebas documentadas.",
    stack: ["GNS3", "Routing", "Switching", "OSPF", "Redes"],
    cover: "/proyectos/redes-infra/GNS3-Topologia/cover.jpg",
    coverAlt: "Topología de red simulada en GNS3",
    gallery: [],
    links: [{ label: "Leer informe", href: "/proyectos/redes-infra/GNS3-Topologia/GNS3-Topologia.pdf" }],
    access: { label: "Caso documentado", detail: "Informe académico disponible." },
    tone: "ink",
  },
  {
    slug: "enlaces-inalambricos",
    title: "Enlaces inalámbricos / PTP + PTMP",
    category: "Redes + seguridad",
    group: "infrastructure",
    year: "2024",
    index: "26",
    summary: "Diseño y optimización de enlaces punto a punto y multipunto con Ubiquiti y Mikrotik.",
    description: ["Selección de equipos, alineación, medición y optimización de enlaces inalámbricos.", "Criterios de cobertura, interferencia y calidad de señal para distintas configuraciones."],
    result: "Una propuesta de conectividad sustentada en mediciones, no en supuestos.",
    stack: ["Ubiquiti", "Mikrotik", "PTP", "PTMP", "Radioenlaces"],
    cover: "/proyectos/redes-infra/Conexiones/cover.jpg",
    coverAlt: "Diagrama de enlaces inalámbricos PTP y PTMP",
    gallery: [],
    links: [{ label: "Leer informe", href: "/proyectos/redes-infra/Conexiones/TRABAJO%20PR%C3%81CTICO%201.pdf" }],
    access: { label: "Caso documentado", detail: "Informe académico disponible." },
    tone: "sand",
  },
  {
    slug: "begapanku",
    title: "Begapanku / Cubo interactivo",
    category: "Diseño + 3D",
    group: "infrastructure",
    year: "2024",
    index: "27",
    summary: "Cubo físico con pantallas, LEDs y Raspberry Pi para resolver acertijos visuales.",
    description: ["Diseño industrial, interfaz y electrónica en un objeto interactivo cognitivo.", "AutoCAD, SketchUp y Figma articulan pantallas táctiles, iluminación y Raspberry Pi."],
    result: "Un producto donde la forma física y el comportamiento digital se explican mutuamente.",
    stack: ["Raspberry Pi", "AutoCAD", "SketchUp", "Figma", "Electrónica"],
    cover: "/proyectos/adobes-3d/begapanku/cover.jpg",
    coverAlt: "Diseño del cubo interactivo Begapanku",
    gallery: [],
    links: [
      { label: "Ver presentación", href: "https://docs.google.com/presentation/d/111Toyag6G2Ynvku2mBkqE5EIeJBR_U-SOjE4qAdgZ08/edit?usp=sharing" },
      { label: "Leer informe", href: "/proyectos/adobes-3d/begapanku/begapanku.pdf" },
    ],
    access: { label: "Caso documentado", detail: "Presentación e informe disponibles." },
    tone: "sand",
  },
  {
    slug: "horno-arduino",
    title: "Control térmico / Arduino",
    category: "Hardware + IoT",
    group: "infrastructure",
    year: "2024",
    index: "28",
    summary: "Control automático de temperatura con sensores y relés para una regulación térmica precisa.",
    description: ["El prototipo mide temperatura y actúa mediante relés para mantener el rango configurado.", "La simulación en Tinkercad valida circuito y lógica antes del armado físico."],
    result: "Un lazo de control entendible, medible y fácil de reproducir.",
    stack: ["Arduino", "Sensores", "Relés", "Tinkercad", "Control"],
    cover: "/proyectos/arduino-iot/horno-arduino/cover.jpg",
    coverAlt: "Circuito del sistema de control térmico con Arduino",
    gallery: [],
    links: [
      { label: "Abrir simulación", href: "https://www.tinkercad.com/things/7zaPoiphSbs-horno-definitivo" },
      { label: "Leer informe", href: "/proyectos/arduino-iot/horno-arduino/Horno-Arduino.pdf" },
    ],
    access: { label: "Caso documentado", detail: "Simulación e informe disponibles." },
    tone: "orange",
  },
];

export const projects = projectEntries.map((project, position) => ({
  ...project,
  index: String(position + 1).padStart(2, "0"),
}));

export const projectGroups: ProjectGroup[] = [
  {
    id: "commerce",
    index: "01",
    label: "Comercio, plataformas y experiencias",
    description: "Tiendas, catálogos, marcas y productos digitales construidos alrededor de una operación real.",
  },
  {
    id: "automation",
    index: "02",
    label: "Sistemas, ERP, bots y automatización",
    description: "Productos separados por función: gestión, asistentes, datos y flujos que conectan operaciones reales.",
  },
  {
    id: "infrastructure",
    index: "03",
    label: "Infraestructura, hardware y 3D",
    description: "Redes, dispositivos y prototipos donde el sistema también ocupa espacio físico.",
  },
];

export const groupedProjects = projectGroups.map((group) => ({
  ...group,
  projects: projects.filter((project) => project.group === group.id),
}));

const featuredOrder = [
  "ceferina-accesorios",
  "agroveterinaria-gross",
  "zubu-agency",
  "facturacion-mercadopago-arca",
  "tienda-mamayucca",
  "tienda-emag",
  "emag-inmersivo-gsap",
  "yeryos",
];

export const featuredProjects = featuredOrder
  .map((slug) => projects.find((project) => project.slug === slug))
  .filter((project): project is Project => Boolean(project));

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}
